#include <avr/io.h>
#include <util/twi.h>

/* I2C protocol (Inter-Integrated Circuit) / TWI (Two Wire Interface):
 * 		a synchronous, multi-master, multi-slave, packet-switched, serial communication bus that allows multiple chips to talk 
 *      using only two wires
 * SCL (Serial Clock):
 * 		Heartbeat of the bus. 
 * 		Wire that carries clock signal generated by Master device, synchornizes the timing of date bits sent between devices.
 * SDA (Serial Data):
 * 		Highway for information.
 * 		Wire that carries actual data bits (address, register, sensor value) back and forth between Master & Slave	
 * Master: (AVR CPU)
 *      Starts conversation & Generate SCL clock
 * Slave: （LED, SENSOR ...）
 *      Listens for its address & Responds to Master
 * 
 * EX00 Purpose:
 *      Verify TWI status of AHT20 by sending START & STOP signal
 * 
 *      AHT20:          Humidity and Temperature Sensor     
 * 		START signal 1: Master is using the bus (occupied) 
 * 		TWINT bit 1:    Slaves are listening & waiting for Master's command & stops SCL clock
 *      WRITE ：        TWI Status: ATH20 ACK(0X18) NACK(0X20)
 *      STOP signal 1:  Bus is free to use
*/

# define MYUBRR  ((F_CPU / (8L * UART_BAUDRATE)) - 1)

void uart_init(void)
{
    UBRR0 = (unsigned int)MYUBRR;           //DS40002061B p.182
    UCSR0A |= (1 << U2X0);                  //Double speed: reduce baud rate error percentage at high speeds
    UCSR0B = (1 << TXEN0)| (1 << RXEN0);    //enable Transmitter(send out) & Receiver
    UCSR0C = (1 << UCSZ01) | (1 << UCSZ00); //set frame format: 8N1 (8-bit/1-byte; No parity check; 1 stop bit(USBS0 = 0))
}

void uart_tx(const char *s)
{
	while (*s)
	{
		while (!(UCSR0A & (1 << UDRE0))) ;   // wait till buffer is empty
		UDR0 = *s++;
	}
}

const char*	i2c_return_code_desc(unsigned char status_code)             // p.227
{
	status_code &= 0xf8; 												//1111 1000
	if (status_code == TW_START)                                        //0x08
		return ("START acknowledge\n\r");                               
    else if (status_code == TW_REP_START)                               //0x10
        return ("REPEATED START acknowledge\n\r");  
    else if (status_code == TW_MT_SLA_ACK)                              //0x18
        return ("Master Transmitter: Slave ACK\n\r");
    else if (status_code == TW_MT_SLA_NACK)
        return ("Master Transmitter : Slave NACK\n\r");                 //0x20
    else if (status_code == TW_MT_DATA_ACK)
        return ("Master Transmitter : Data ACK\n\r");                   //0x28
    else if (status_code == TW_MT_DATA_NACK)
        return ("Master Transmitter: Data NACK\n\r");                   //0x30
    else if (status_code == TW_MR_SLA_ACK)
        return ("Master Receiver : Slave ACK\n\r");                     //0x40
    else if (status_code == TW_MR_SLA_NACK)
        return ("Master Receiver : Slave NACK\n\r");                    //0x38
    else if (status_code == TW_MR_DATA_ACK)                             //0x50
        return ("Master Receiver : Data ACK\n\r");
    else if (status_code == TW_MR_DATA_NACK)                            //0x58
        return ("Master Receiver : Data NACK\n\r");
    else if (status_code == TW_MT_ARB_LOST || status_code == TW_MR_ARB_LOST) //0x38
        return ("Arbitration Lost\n\r");
    else if (status_code == TW_ST_SLA_ACK)
        return ("Slave Transmitter : Slave ACK\n\r");
    else if (status_code == TW_ST_ARB_LOST_SLA_ACK)
        return ("Arbitration Lost in SLA+R/W, Slave ACK\n\r");
    else if (status_code == TW_ST_DATA_ACK)
        return ("Slave Transmitter : Data ACK\n\r");
    else if (status_code == TW_ST_DATA_NACK)
        return ("Slave Transmitter : Data NACK\n\r");
    else if (status_code == TW_ST_LAST_DATA)
        return ("Slave Transmitter : Last Data\n\r");
    else if (status_code == TW_SR_SLA_ACK)
        return ("Slave Receiver : Slave ACK\n\r");
    else if (status_code == TW_SR_ARB_LOST_SLA_ACK)
        return ("Arbitration Lost in SLA+R/W, Slave ACK\n\r");
    else if (status_code == TW_SR_GCALL_ACK)
        return ("General Call : Slave ACK\n\r");
    else if (status_code == TW_SR_ARB_LOST_GCALL_ACK)
        return ("Arbitration Lost in General Call, Slave ACK\n\r");
    else if (status_code == TW_SR_DATA_ACK)
        return ("Slave Receiver : Data ACK\n\r");
    else if (status_code == TW_SR_DATA_NACK)
        return ("Slave Receiver : Data NACK\n\r");
    else if (status_code == TW_SR_GCALL_DATA_ACK)
        return ("General Call : Data ACK\n\r");
    else if (status_code == TW_SR_GCALL_DATA_NACK)
        return ("General Call : Data NACK\n\r");
    else if (status_code == TW_SR_STOP)
        return ("Slave Receiver : STOP received\n\r");
    else if (status_code == TW_NO_INFO)
        return ("No state information available\n\r");
    else if (status_code == TW_BUS_ERROR)
        return ("Bus Error\n\r");
    else
        return ("Unknown Status Code\n\r");
}

void    print_hex(uint8_t n)
{
    char hex[] = "0123456789abcdef";
    char str[2] = {0, 0};

    str[0] = hex[(n >> 4) & 0x0f];
    uart_tx(str);                     // 1111 1010 -> 0000 [1111]
    str[0] = hex[n & 0x0f];
    uart_tx(str);                     // 1111 1010 -> 1111 [1010]
}
										 
void i2c_init(void)
{
	TWBR = 72;								 // TWI Bit Rate Register = Value of the TWI Bit Rate Register
										     // SCL_frequency = F_CPU / (16 + 2 * TWBR * Prescaler) = 100kHz (P.222)
	TWSR &= ~((1 << TWPS1) | (1 << TWPS0));  // TWI Status Register (p.241) Prescaler 1
	TWCR = (1 << TWEN);						 // TWI Control Register: enable TWI operation & interface
}

void i2c_start(void)								  // Send I2C START Condition
{
	uart_tx("i2c_status: ");
	TWCR = (1 << TWINT) | (1 << TWSTA) | (1 << TWEN); // (p.239) TWI Control Register
													  // TWI Interrupt Flag: 1 (finish & waiting for new instruction)
													  //  == a signal that commands the TWI hardware to perform the next action on the bus
									   				  // TWI Start condition bit：send START signal 
													  // TWI Enable bit: enable TWI operation & interface
	while (!(TWCR & (1 << TWINT)));					  // wait till START signal being sent
	print_hex(TW_STATUS);                             // (p.227)should print 08 (0x08 8-bit): START signal has been sent
    uart_tx(", ");
    uart_tx(i2c_return_code_desc(TWSR));              
}

void i2c_write(unsigned char data)
{
    uart_tx("i2c_status: ");
    TWDR = (uint8_t)data;                             // Data Register
    TWCR = (1 << TWINT) | (1 << TWEN);
    while (!(TWCR & (1 << TWINT)));                   // Wait for TWINT flag (indicates byte sent and ACK/NACK received)
    print_hex(TW_STATUS);                             // should print 18: (p.227)
                                                      // SLAVE+WRITE has been transmitted; ACK has been received
    uart_tx(", ");
    uart_tx(i2c_return_code_desc(TWSR));
}

void i2c_stop(void)									  // Send I2C STOP Condition
{
	TWCR = (1 << TWINT) | (1 << TWSTO) | (1 << TWEN); // (p.240) TWI Stop condition bit: send STOP signal
													  // TWSTO bit is cleared automatically
	for (volatile int i = 0; i < 100; i++);			  // wait till STOP condition bit is cleared
}

int main(void)
{
	uart_init();
    i2c_init();

	while (1)
	{
		uart_tx("TESTING...\n\r");
		i2c_start();									// 1. send START signal & wait for hardware to confirm
		// TWCR = (1 << TWINT) | (1 << TWEN);			// clear TWINT interrupt flag (tells hardware to perform new bus operation)
		// while (!(TWCR & (1 << TWINT)));				// wait till hardware finish operation & set TWINT 1 again
		i2c_write(0x38 << 1);                           // Expected Status: 18 (ACK) or 20 (NACK) [0011 100]0-> [0111 00]0 last-bit(WRITE)
                                                        // AHT20 datasheet "V1.0" May 2021 (p.12)
                                                        // 7-bit Slave Address(0x38) + 1-bit R/W bit(0x01)
        i2c_stop();										// 2. send STOP signal & release bus
		for (volatile long i = 0; i < 1000000; i++);    // 3. delay & prevent bus flooding
	}
	return 0;
}
