#include <avr/io.h>
#include <util/twi.h>
#include <util/delay.h>

/* --AHT20 datasheet "V1.0" May 2021-- 
 * I2C protocol (Inter-Integrated Circuit) / TWI (Two Wire Interface):
 * 		a synchronous, multi-master, multi-slave, packet-switched, serial communication bus that allows multiple chips to talk 
 *      using only two wires
 * SCL (Serial Clock):
 * 		Heartbeat of the bus. 
 * 		Wire that carries clock signal generated by Master device, synchornizes the timing of date bits sent between devices.
 * SDA (Serial Data):
 * 		Highway for information.
 * 		Wire that carries actual data bits (address, register, sensor value) back and forth between Master & Slave	
 * Master: (AVR CPU)
 *      Starts conversation & Generate SCL clock
 * Slave: （LED, SENSOR ...）
 *      Listens for its address & Responds to Master
 * 
 * EX01 Purpose:
 *      Implemet TWI (AVR MCU & AHT20 sensor) to retrieve raw data(hexadecimal) in Write-Wait-Read cycle
 *      AHT20:        Humidity and Temperature Sensor     
 *      WRITE:        Send SLA+W (0x70) + Command (0xAC)
 *      TWI Status:   Master Transmitted SLA+W & ACK received (0x18)
 *      Read :        Send SLA+R (0x71)
 *      TWI Status:   Master Transmitted SLA+R & ACK received (0x40)
 * 
 * AHT20 Data Sequence (7 Bytes) (p.13 Picture):
 * - Byte 1:   Status Word (Bit[7]: Busy, Bit[3]: Calibrated).
 * - Byte 2-6: Compressed Humidity & Temperature Raw Data (20-bit each).
 * - Byte 7:   CRC(Cyclic Redundancy Check) Checksum for error detection. (p.12 check if CRC is correct == X^8+X^5+X^4+1（0x31 [1 [0011 0001]]）)
 *
 * ACK/NACK Logic during Read:
 * - Send TWEA (ACK) for bytes 1 through 6 to keep the sensor transmitting.
 * - Send NACK for the 7th byte to signal "End of Reception" to the Slave.
*/

# define MYUBRR  ((F_CPU / (8L * UART_BAUDRATE)) - 1)

void uart_init(void)
{
    UBRR0 = (unsigned int)MYUBRR;           //DS40002061B p.182
    UCSR0A |= (1 << U2X0);                  //Double speed: reduce baud rate error percentage at high speeds
    UCSR0B = (1 << TXEN0)| (1 << RXEN0);    //enable Transmitter(send out) & Receiver
    UCSR0C = (1 << UCSZ01) | (1 << UCSZ00); //set frame format: 8N1 (8-bit/1-byte; No parity check; 1 stop bit(USBS0 = 0))
}

void uart_tx(char c)
{
	while (!(UCSR0A & (1 << UDRE0))) ;   // wait till buffer is empty
	UDR0 = c;
}

void    print_hex_value(char c)
{
    char hex[] = "0123456789abcdef";
    char high = hex[(c >> 4) & 0x0f];
    char low = hex[c & 0x0f];

    uart_tx(high);
    uart_tx(low);
    uart_tx(' ');
}
										 
void i2c_init(void)
{
	TWBR = 72;								 // TWI Bit Rate Register = Value of the TWI Bit Rate Register
										     // SCL_frequency = F_CPU / (16 + 2 * TWBR * Prescaler) = 100kHz (P.222)
	TWSR &= ~((1 << TWPS1) | (1 << TWPS0));  // TWI Status Register (p.241) Prescaler 1
	TWCR = (1 << TWEN);						 // TWI Control Register: enable TWI operation & interface
}

void i2c_start(void)								  // Send I2C START Condition
{
	TWCR = (1 << TWINT) | (1 << TWSTA) | (1 << TWEN); // (p.239) TWI Control Register
													  // TWI Interrupt Flag: 1 (finish & waiting for new instruction)
													  //  == a signal that commands the TWI hardware to perform the next action on the bus
									   				  // TWI Start condition bit：send START signal 
													  // TWI Enable bit: enable TWI operation & interface
	while (!(TWCR & (1 << TWINT)));					  // wait till START signal being sent           
}

unsigned char i2c_read_ack(void)                      // [0000 00]00 -> ACK
{
    TWCR = (1 << TWINT) | (1 << TWEN) | (1 << TWEA);  // TWEA: TWI Enable Acknowledge Bit
    while (!(TWCR & (1 << TWINT)));                     
    return TWDR;                                      // contains AHT20's STATUS, Humidity/Temperature, CRC
}

unsigned char i2c_read_nack(void)                     // 0000 000[0] -> NACK == Finish reading
{
    TWCR = (1 << TWINT) | (1 << TWEN);                // read but Not enable ACK
    while (!(TWCR & (1 << TWINT)));
    return TWDR;
}

void i2c_write(unsigned char data)
{
    TWDR = (uint8_t)data;                             // Data Register
    TWCR = (1 << TWINT) | (1 << TWEN);
    while (!(TWCR & (1 << TWINT)));                   // Wait for TWINT flag (indicates byte sent and ACK/NACK received)
}

void i2c_read_and_print(int is_last_bit)
{
    if (is_last_bit)
        TWCR = (1 << TWINT) | (1 << TWEN);            // last-bit, Not enable ACK
    else
        TWCR = (1 << TWINT) | (1 << TWEN) | (1 << TWEA);
    while (!(TWCR & (1 << TWINT)));
    print_hex_value(TWDR);    
}

void i2c_stop(void)									  // Send I2C STOP Condition
{
	TWCR = (1 << TWINT) | (1 << TWSTO) | (1 << TWEN); // (p.240) TWI Stop condition bit: send STOP signal
													  // TWSTO bit is cleared automatically
	for (volatile int i = 0; i < 100; i++);			  // wait till STOP condition bit is cleared
}

int main(void)
{
	uart_init();
    i2c_init();

    //Step 1: Power-on and Status Check (p.12 step 1)
    _delay_ms(100);                                         // 1. wait 100ms
    i2c_start();
    i2c_write((0x38 << 1) | 1);                             // 2. Send 0x71 (SLA+R) to get status 0111 000[1]Read
    unsigned char status = i2c_read_nack();                 // Read one byte
    i2c_stop();
    if (!(status & 0x08))                                   // 3. Check Bit 3 (Calibration bit)
    {
        i2c_start();
        i2c_write(0x38 << 1);
        i2c_write(0xBE);                                    // Calibration command
        i2c_write(0x08);
        i2c_write(0x00);
        i2c_stop();
        _delay_ms(10);                                      // Wait for calibration to take effect
    }
    
	while (1)
	{
        //Step 2: Trigger Humidity/Tempeture Measurement 
		i2c_start();						// 1. send START signal & wait for hardware to confirm
		i2c_write(0x38 << 1);               // 2. (SLA+W) AHT20-Address:0011 100[0]-> 0111 00[0](WRITE); AHT20-datasheet(p.12)
        i2c_write(0XAC);                    // Send "Trigger Measurement" command(0xAC) followed by required parameters (0x33, 0x00)
        i2c_write(0X33);
        i2c_write(0X00);
        i2c_stop();		                    // 3. send STOP signal & release bus
        _delay_ms(80);                      // 4. wait for measurement
        
        //Step 3: Read 7 Bytes
        i2c_start();
        i2c_write((0x38 << 1) | 1);         // SLA+R
		for (int i = 0; i < 7; i++)         // Send ACK for first 6 bytes, NACK for the last (CRC) byte (Cyclic Redundancy Check)
        {
            if (i == 6)
                i2c_read_and_print(1);
            else
                i2c_read_and_print(0);
        }
        i2c_stop();

        uart_tx('\n');
        uart_tx('\r');
        _delay_ms(2000);                     // AHT20-datasheet (p.7)"data collection cycle should be greater than 1 second/time"
	}
	return 0;
}


/*
I2C 总线比作一条电话线：

    i2c_start()：相当于拿起电话。

    i2c_write(地址)：相当于拨通 AHT20 的分机号。

    i2c_write(数据)：相当于你在电话里说的一句话或一个单词。

    i2c_stop()：相当于挂断电话。
*/